---

- name: restart docker
  systemd:
    name: docker
    state: restarted
    daemon-reload: yes
  when: not docker_service_status_changed | default(false) | bool

- name: restart udev
  service:
    name: systemd-udevd
    state: restarted
